---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: rancher/dapper:v0.4.1
    commands:
      - dapper ci
    privileged: true
    volumes:
    - name: docker
      path: /var/run/docker.sock
    when:
      event:
        - push
        - pull_request
        - tag

  - name: github_binary_prerelease
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      checksum:
        - sha256
      files:
        - bin/*
      prerelease: true
      title: "Pre-release ${DRONE_TAG}"
    when:
      event:
        - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

node:
  instance: agent-amd64
